image: tomeuv/virgl-ci:latest

cache:
  paths:
    - ccache/
    - install-prefix/

before_script:
   - export ROOT_DIR=${PWD}

   - export GOPATH=/usr/local/go
   - export PATH=$PATH:$GOPATH/bin
   - export PATH="/usr/lib/ccache:$PATH"
   - mkdir -p ccache
   - export CCACHE_BASEDIR=$ROOT_DIR
   - export CCACHE_DIR=$ROOT_DIR/ccache

   - ccache -s

   - export LD_LIBRARY_PATH=$ROOT_DIR/install-prefix/lib64:$ROOT_DIR/install-prefix/lib
   - export PKG_CONFIG_PATH=$ROOT_DIR/install-prefix/lib/pkgconfig:$ROOT_DIR/install-prefix/lib64/pkgconfig:$ROOT_DIR/install-prefix/share/pkgconfig
   - export LDFLAGS="-L$ROOT_DIR/install-prefix/lib64 -L$ROOT_DIR/install-prefix/lib64"

stages:
   - build
   - test

build:
  stage: build
  script:
   - git clone --depth 1 https://github.com/anholt/libepoxy.git
   - cd libepoxy
   - ./autogen.sh --prefix=$ROOT_DIR/install-prefix
   - make -j$(nproc) install
   - cd ..

   - git clone --depth 1 git://anongit.freedesktop.org/mesa/mesa
   - cd mesa
   - ./autogen.sh --prefix=$ROOT_DIR/install-prefix --enable-gles2 --with-platforms="drm x11 wayland" --with-dri-drivers= --with-gallium-drivers="swrast virgl" --enable-debug --disable-glx --disable-omx-tizonia
   - make -j$(nproc) install
   - cd ..

   - ./autogen.sh --prefix=$ROOT_DIR/install-prefix
   - make -j$(nproc) install

   - git clone --depth 1 https://gitlab.collabora.com/tomeu/qemu.git
   - cd qemu
   - ./configure --prefix=$ROOT_DIR/install-prefix --target-list=x86_64-softmmu --enable-kvm --enable-virglrenderer --enable-debug --disable-werror
   - make -j$(nproc) install
   - cd ..

   - git clone --depth 1 https://github.com/KhronosGroup/VK-GL-CTS.git
   - cd VK-GL-CTS
   - mkdir build
   - cd build
   - cmake .. -DDEQP_TARGET=wayland -DGLCTS_GTF_TARGET=gles2
   - make -j$(nproc)
   - cp -rf ../../VK-GL-CTS $ROOT_DIR/install-prefix/.
   - cd ..

test:
  stage: test
  script:
  - export XDG_RUNTIME_DIR=/tmp
  - export WAYLAND_DISPLAY=wayland-0
  - nohup weston --backend=headless-backend.so &
  - sleep 2
  - ln -s $ROOT_DIR/install-prefix/bin/qemu-system-x86_64 /usr/bin/qemu-system-x86_64
  - fakemachine -v $ROOT_DIR/install-prefix:$ROOT_DIR/install-prefix systemctl start weston

