image: docker:latest

cache:
  paths:
    - ccache/

stages:
  - build_and_test

build_and_test:
  stage: build_and_test
  services:
    - docker:dind
  script:
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
   - docker pull $CI_REGISTRY_IMAGE:latest || true  # Just for the cache
   - docker build -t $CI_REGISTRY_IMAGE --cache-from $CI_REGISTRY_IMAGE:latest ci
   - docker push $CI_REGISTRY_IMAGE:latest  # Just for the cache
   - docker run $CI_REGISTRY_IMAGE:latest fakemachine -v /etc/pam.d:/etc/pam.d -v $PWD:$PWD sh $PWD/run-deqp.sh || true

