image: docker:latest

cache:
  paths:
    - ccache/

stages:
  - build_and_test

build_and_test:
  stage: build_and_test
  services:
    - docker:dind
  script:
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
   - docker build ci
   - docker push $CI_REGISTRY_IMAGE:latest
#   - fakemachine -v $PWD:$PWD sh $PWD/run-deqp.sh || true

