image: tomeuv/virgl-ci:latest

cache:
  paths:
    - ccache/
    - install-prefix/

before_script:
   - export ROOT_DIR=${PWD}

   - export GOPATH=/usr/local/go
   - export PATH=$PATH:$GOPATH/bin
   - export PATH="/usr/lib/ccache:$PATH"
   - mkdir -p ccache
   - export CCACHE_BASEDIR=$ROOT_DIR
   - export CCACHE_DIR=$ROOT_DIR/ccache

   - ccache -s

   - export LD_LIBRARY_PATH=$ROOT_DIR/install-prefix/lib64:$ROOT_DIR/install-prefix/lib
   - export PKG_CONFIG_PATH=$ROOT_DIR/install-prefix/lib/pkgconfig:$ROOT_DIR/install-prefix/lib64/pkgconfig:$ROOT_DIR/install-prefix/share/pkgconfig
   - export LDFLAGS="-L$ROOT_DIR/install-prefix/lib64 -L$ROOT_DIR/install-prefix/lib64"

test:
  stage: test
  script:
  - export XDG_RUNTIME_DIR=/tmp
  - export WAYLAND_DISPLAY=wayland-0
  - nohup weston --backend=headless-backend.so &
  - sleep 2
  - fakemachine --help

