image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build_and_test

build_and_test:
  stage: build_and_test
  services:
    - docker:dind
  script:
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
   - docker pull $CI_REGISTRY_IMAGE:latest || true  # Just for the cache
   - docker build --build-arg CI_COMMIT_SHA=$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE --cache-from $CI_REGISTRY_IMAGE:latest ci
   - docker push $CI_REGISTRY_IMAGE:latest  # Just for the cache
   - docker run --device=/dev/kvm -v $PWD:/virglrenderer $CI_REGISTRY_IMAGE:latest sh /virglrenderer/ci/run-tests.sh

